services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    umanit_block_collection.block_manager.faq:
        class: Umanit\BlockCollectionBundle\BlockManager\FaqBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.image:
        class: Umanit\BlockCollectionBundle\BlockManager\ImageBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.images_list:
        class: Umanit\BlockCollectionBundle\BlockManager\ImagesListBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.link:
        class: Umanit\BlockCollectionBundle\BlockManager\LinkBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.quote:
        class: Umanit\BlockCollectionBundle\BlockManager\QuoteBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.video:
        class: Umanit\BlockCollectionBundle\BlockManager\VideoBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']

    umanit_block_collection.block_manager.wysiwyg:
        class: Umanit\BlockCollectionBundle\BlockManager\WysiwygBlockManager
        arguments: ['@twig']
        tags: ['umanit_block.manager']
